

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Deploy to NCP Server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        SSH_KEY: ${{ secrets.KEY }}
      run: |
        # Save SSH key and set permissions
        echo "${SSH_KEY}" > private_key
        chmod 600 private_key

        # Define remote server path
        REMOTE_DIR="/home/${USER}/app"

        # Copy build artifacts to the server
        scp -i private_key -r build/libs/*.jar ${USER}@${HOST}:${REMOTE_DIR}

        # SSH into the server and restart the application
        ssh -i private_key ${USER}@${HOST} << EOF
          cd ${REMOTE_DIR}
          # (Optional) Stop existing application
          pkill -f 'java -jar' || echo "No existing application running"

          # Start new application
          nohup java -jar *.jar > app.log 2>&1 &
        EOF


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
