name: Deploy Spring Boot Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 빌드 및 테스트 (테스트 환경에서 실행)
      - name: Build project
        run: ./gradlew build
        env:
          SPRING_PROFILES_ACTIVE: test # GitHub Actions에서 테스트 프로파일 활성화

#      # 3. Gradle 빌드
#      - name: Build project
#        run: ./gradlew build

      # 4. 서버로 JAR 파일 전송 및 실행
      - name: Deploy JAR to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping existing application..."
            pkill -f 'java -jar' || true

            echo "Uploading JAR file..."
            scp build/libs/*.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/branchify/app.jar

            echo "Starting application..."
            nohup java -jar /var/www/branchify/app.jar > /var/www/branchify/logs/app.log 2>&1 &









